source("loadPowerData.R")
power.data <- loadPowerData()
hist(power.data$Global_active_power, col=c("red"), main="Global Active Power", xlab = "Global Active Power (killowatts)")
dev.copy(png, file = "plot1.png", width=480, height=480)
dev.off()